blank_issues_enabled: false
contact_links:
  - name: Ask a question on Discussions area (NEW!)
    url: https://github.com/node-saml/node-saml/discussions
    about: Recommended place for questions, debates, consultation.
  - name: Ask a question on StackOverflow
    url: https://stackoverflow.com/questions/tagged/node-saml
